import argparse
import json
import sys
from pathlib import Path
from typing import List, Tuple

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


class InMemoryVectorStore:
    def __init__(self):
        self.texts: List[str] = []
        self.metadata: List[dict] = []
        self.embeddings: np.ndarray | None = None

    def build(self, texts: List[str], metadata: List[dict], embed_fn) -> None:
        vectors = [np.asarray(embed_fn(t), dtype=float) for t in texts]
        self.texts = texts
        self.metadata = metadata
        self.embeddings = np.vstack(vectors) if vectors else np.zeros((0, 0), dtype=float)

    def search(self, query_vec: np.ndarray, top_k: int = 3) -> List[Tuple[int, float]]:
        if self.embeddings is None or self.embeddings.size == 0:
            return []

        emb = self.embeddings
        q = query_vec.astype(float)

        emb_norm = np.linalg.norm(emb, axis=1)
        q_norm = float(np.linalg.norm(q))
        denom = emb_norm * q_norm
        denom[denom == 0] = 1e-12

        scores = (emb @ q) / denom
        idx = np.argsort(scores)[::-1][:top_k]
        return [(int(i), float(scores[i])) for i in idx]


def load_cleaned_records(cleaned_path: Path) -> List[dict]:
    if not cleaned_path.exists():
        raise FileNotFoundError(
            f"Cleaned file not found: {cleaned_path}. Run check_sql_quality.py first."
        )
    return json.loads(cleaned_path.read_text(encoding="utf-8"))


def get_embedder(model_name: str):
    try:
        from sentence_transformers import SentenceTransformer

        model = SentenceTransformer(model_name)
        return lambda text: model.encode(text)
    except Exception:
        # Fallback to project embed function if model download is unavailable.
        from app.services.embedding_service import embed_text

        return embed_text


def main() -> None:
    parser = argparse.ArgumentParser(description="Quick RAG retrieval test on cleaned SQL material")
    parser.add_argument("--cleaned-path", default="cleaned_material.json", help="Path to cleaned JSON generated by check_sql_quality.py")
    parser.add_argument("--top-k", type=int, default=3, help="Top-k retrieval size")
    parser.add_argument(
        "--model",
        default="sentence-transformers/all-MiniLM-L6-v2",
        help="Embedding model name",
    )
    args = parser.parse_args()

    records = load_cleaned_records(Path(args.cleaned_path))
    if not records:
        print("No cleaned records available. Nothing to index.")
        return

    texts = [r.get("text", "") for r in records if r.get("text")]
    metas = [r.get("metadata", {}) for r in records if r.get("text")]

    if not texts:
        print("No usable text fields found in cleaned records.")
        return

    embed_fn = get_embedder(args.model)
    store = InMemoryVectorStore()
    store.build(texts, metas, embed_fn)

    queries = [
        "什么是 CSMA/CD？",
        "TCP 拥塞控制方法有哪些？",
        "计算机网络课程设计要求是什么？",
    ]

    for q in queries:
        q_vec = np.asarray(embed_fn(q), dtype=float)
        hits = store.search(q_vec, top_k=args.top_k)

        print("=" * 72)
        print(f"Query: {q}")
        if not hits:
            print("No hits")
            continue

        for rank, (idx, score) in enumerate(hits, start=1):
            snippet = texts[idx][:220].replace("\n", " ")
            title = metas[idx].get("title") if isinstance(metas[idx], dict) else None
            print(f"[{rank}] score={score:.4f} title={title}")
            print(f"    {snippet}")


if __name__ == "__main__":
    main()
